- name: Install packages
  apt: name={{ item }} state=present update_cache=yes cache_valid_time=86400
  with_items:
    - nano
    - build-essential
    - git-core
    - apache2
  tags: apt
- name: Create ansible user
  sudo: true
  user: name={{user}} generate_ssh_key=yes createhome=yes state=present shell=/bin/bash
  tags: create_user
- name: Copy deploy key
  copy: src={{deploy_key_file}} dest=/home/{{user}}
- name: Clone repo
  sudo: True
  sudo_user: '{{user}}'
  git:
    accept_hostkey: yes
    clone: yes
    dest: /home/{{user}}/www
    repo: "{{git_repo}}"
    update: no
    key_file: "{{key_file_path}}"
  tags: gitclone