---
- hosts: webservers
  sudo: true

  vars:
    user: ansible

  roles:
    - role: ansible_site
      deploy_key_file: deploy_key_for_supersite
      key_file_path: "/home/{{user}}/deploy_key_for_supersite"
      git_repo: git@github.com:jloosfelt/supersite.git
    - role: vhost
      user: '{{ user }}'
      base_dir: /home/{{user}}/www
      url: ansible.dev
      tags:
      - vhost