- name: Check if database {{ db_name }} exists
  shell: mysql -e "SHOW databases" | grep {{ db_name }}
  register: databases
  ignore_errors: True
  tags: create_mysql_database

- name: Create database {{ db_name }}
  mysql_db:
    name: "{{ db_name }}"
    state: present
    collation: utf8_general_ci
    encoding: utf8
  when: databases|failed
  tags: create_mysql_database

- name: Create user {{ db_login }} is present
  mysql_user:
    name: "{{ db_login }}"
    password: "{{ db_passwd }}"
    priv: "{{ db_name }}.*:ALL"
  tags: create_mysql_user

- name: Copy dump {{ dump_file }} to tmp
  copy: src={{ dump_file }} dest=/tmp
  when: dump_file is defined
  tags:
  - dump
  - create_mysql_database

- name: Restore dump to {{ db_name }}
  mysql_db: name={{ db_name }} state=import target=/tmp/{{ dump_file }}
  when: dump_file is defined
  tags:
  - dump
  - create_mysql_database
